### ISSUE TITLE
AttributeError: module 'google.cloud.vision' has no attribute 'types'

### ISSUE THREAD

**Issue by prabowomurti** [lutzkuen/receipt-parser#1]
https://github.com/lutzkuen/receipt-parser/blob/13b5d283680f24a30ebf266a7fd5d8ef6164b70c/examples/gcloud_example.py#L15

I get the above error message and change 

`image = vision.types.Image(content=content)`

to

`image = vision.Image(content=content)`

**Comment by lutzkuen** [comment]
Thanks, fixed. Seems like it was moved with the release of google-cloud-vision 2.0.
